"""empty message

Revision ID: 65fffced34fe
Revises: 76afa8abcaf2
Create Date: 2021-04-06 11:17:31.120175

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '65fffced34fe'
down_revision = '76afa8abcaf2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
