"""empty message

Revision ID: 76afa8abcaf2
Revises: 
Create Date: 2021-04-06 11:17:16.117696

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76afa8abcaf2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
